### ISSUE TITLE
Add gutter icons for successful and/or failed proofs

### ISSUE THREAD

**Issue by xldenis** [creusot-rs/creusot-ide#1]
The Dafny IDE (and Viper IDE) both use gutter icons to show the current proof state, in Dafny this is implemented using the VSCode Tests API (I think that's what it's called). Otherwise its quite hard to tell if a proof was successful or just not loaded / not present :P

**Comment by Lysxia** [comment]
Added in e220e4eb211d77f8e095b4aa487944956f63ca88! (See cbe07a4e6d3c09b7de0c5cc3681905f7960fe41f for usage)
