### ISSUE TITLE
See through type synonyms

### ISSUE THREAD

**Issue by Lysxia** [creusot-rs/creusot-ide#9]
CreusotIDE is confused by type synonyms when trying to match Rust `impl` with their Coma module(s). For example

```
type Ptr = usize
impl IndexLogic<Ptr> for Memory {
  fn index(...) { }
}
```

becomes this Coma module:

```
module M_list_reversal_lasso__qyi13715866738248475091__index
  [#"../list_reversal_lasso.rs" 30 4 30 35]
  (* <Memory as std::ops::Index<usize>> *)
```

Note that `Ptr` gets normalized to `usize`. When CreusotIDE encounters `IndexLogic<Ptr>` it doesn't know to match it with `std::ops::Index<usize>`.

Possible fixes:

- Parse `type` annotations (but that won't work with type equalities from other modules)
- Have Creusot output the `impl` head as it appears in the source in the `module` comment, instead of a normalized form.

**Comment by xldenis** [comment]
The second option isn't feasible, the type synonym isn't "queryable" in the compiler output.

**Comment by xldenis** [comment]
I fear that this is the sort of long-tail issue where we need this to be in rust, not a standalone ocaml binary. Note we can also have associated types as impl heads.

**Comment by xldenis** [comment]
Would it be feasible to establish the link "backwards" going from the coma to the Rust? That seems like it would be resilient to any modifications made in Rust and new features.
